job/urls.py
from django.urls import include, path

from . import generate_skills, job_description_algorithm, views
from .gpt_calls import execute_input, generate_mcqs, get_skills_from_chatgpt
from .views import enter_job_description

app_name = "job"


urlpatterns = [
    path("create-job/", views.create_job, name="create-job"),
    path("job_type_view/", views.job_type_view, name="job_type_view"),
    path("update-job/<int:pk>/", views.update_job, name="update-job"),
    path("apply/<int:job_id>/", views.apply_job, name="apply_job"),
    path("details/<int:job_id>/", views.job_details, name="job_details"),
    path("job-details/<int:job_id>/", views.job_listing_details, name="job_listing_details"),
    path("confirm/<int:job_id>/", views.confirm_evaluation, name="confirm_evaluation"),
    path("enter-job-description/", enter_job_description, name="enter_job_description"),
    path("job/<int:job_id>/save/", views.save_job, name="save_job"),
    path(
        "save-job/<int:job_id>/", views.save_job_not_ajax, name="save_job_not_ajax"
    ),  # Add this line
    path("saved-jobs/", views.saved_jobs_view, name="view_saved_jobs"),
    path("saved-job/<int:saved_job_id>/delete/", views.delete_saved_job, name="delete_saved_job"),
    path("results/<int:job_id>/", views.evaluation_results, name="evaluation_results"),
    path("update/<int:job_id>/", views.update_job, name="update_job"),
    path("incomplete-jobs/", views.incomplete_jobs_view, name="incomplete_jobs"),
    path("save_video/", views.save_video, name="save_video"),
    # Compiler path
    path("run-code/", views.run_code, name="run_code"),
    path("success/", views.success_page, name="success_page"),
    path("fail/", views.fail_page, name="fail_page"),
    # skills
    path("select-skills/", views.select_skills, name="select_skills"),
    # quiz
    path("job/<int:job_id>/answer/", views.answer_job_questions, name="answer_job_questions"),
    path(
        "answer/<int:job_id>/success", views.job_application_success, name="job_application_success"
    ),
    path(
        "get_questions_for_skill/<int:skill_id>/",
        views.get_questions_for_skill,
        name="get_questions_for_skill",
    ),
    path("save_responses/", views.save_responses, name="save_responses"),
    path("generate_skills/", get_skills_from_chatgpt, name="generate_skills"),
    path("generate_mcqs/", generate_mcqs, name="generate_mcqs"),
    path("execute_input/", execute_input, name="execute_input"),
    # For generating MCQs per skill when creatung a job, this takes the job_title , the entry level and the skills
    path("generate-questions/", generate_skills.generate_questions_view, name="generate_questions"),
    path(
        "extract-technical-skills/",
        job_description_algorithm.extract_technical_skills_endpoint,
        name="extract_technical_skills",
    ),
    path("applied-jobs/", views.user_applied_jobs, name="applied_jobs"),
    path(
        "withdraw-application/<int:job_id>/",
        views.withdraw_application,
        name="withdraw_application",
    ),
    path("save-job/<int:job_id>/", views.save_job, name="save_job"),
    path("remove-saved-job/<int:job_id>/", views.remove_saved_job, name="remove_saved_job"),
    path("saved-jobs/", views.saved_jobs_view, name="saved_jobs"),
    path(
        "jobs/<int:job_id>/shortlist/<int:candidate_id>/",
        views.shortlist_candidate,
        name="shortlist_candidate",
    ),
    path("jobs/shortlisted/<int:company_id>/", views.shortlisted_candidates, name="shortlisted"),
    path(
        "jobs/<int:job_id>/decline/<int:candidate_id>/",
        views.decline_candidate,
        name="decline_candidate",
    ),
    path("issue/<int:job_id>/", views.report_test, name="report_test"),
]

messaging/urls.py
from django.urls import path

from . import views

app_name = "messaging"

urlpatterns = [
    path("inbox/", views.inbox_view, name="inbox"),
    path("chat/<int:conversation_id>/", views.chat_view, name="chat"),
    path("send_message/<int:conversation_id>/", views.send_message, name="send_message"),
    path("start_chat/<int:user_id>/", views.start_chat, name="start_chat"),  # New URL pattern
]

notifications/urls.py
from django.urls import path

from . import views

app_name = "notifications"

urlpatterns = [
    # URL for viewing notifications
    path("", views.user_notifications, name="user_notifications"),
    # URL for marking a notification as read
    path(
        "notifications/read/<int:notification_id>/",
        views.mark_notification_as_read,
        name="mark_notification_as_read",
    ),
]

umemployed/urls.py
from allauth.account.views import confirm_email, email_verification_sent
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import JsonResponse
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

from users import views
from users.views import CustomConfirmEmailView, custom_404_view, custom_500_view

# Define custom error handlers
handler404 = "users.views.custom_404_view"
handler500 = "users.views.custom_500_view"

schema_view = get_schema_view(
    openapi.Info(
        title="Umemployed API",
        default_version="v1",
        description="API documentation for Umemployed",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="info@umemployed.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(AllowAny,),
)


def show_settings(request):
    return JsonResponse(
        {
            "CSRF_TRUSTED_ORIGINS": settings.CSRF_TRUSTED_ORIGINS,
            "ALLOWED_HOSTS": settings.ALLOWED_HOSTS,
            "SECURE_PROXY_SSL_HEADER": settings.SECURE_PROXY_SSL_HEADER,
            "USE_X_FORWARDED_HOST": settings.USE_X_FORWARDED_HOST,
        }
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/user/", include("users.urls")),
    path("api/users/", include("users.api.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("jobs/", views.home, name="home"),
    path("", views.index, name="index"),
    path("accounts/", include("allauth.urls")),
    path("social-auth/", include(("social_django.urls", "social"), namespace="social")),
    # urls for the password reset with email
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="password_reset/passwordReset.html"),
        name="reset_password",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/passwordResetSent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/passwordResetForm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/passwordResetDone.html"
        ),
        name="password_reset_complete",
    ),
    # for the company app
    path("company/", include("company.urls")),
    path("api/company/", include("company.api.urls")),
    # for the resume app
    path("resume/", include("resume.urls")),
    path("api/resume/", include("resume.api.urls")),
    path("job/", include("job.urls")),
    path("api/job/", include("job.api.urls")),
    path("jobs/", include("website.urls")),
    path("onboarding/", include("onboarding.urls")),
    path("assessments/", include("asseessments.urls")),
    path("posts/", include("social_features.urls")),
    path("messages/", include("messaging.urls")),
    path("api/messages/", include("messaging.api.urls")),
    path("notifications/", include("notifications.urls")),
    path("api/notifications/", include("notifications.api.urls")),
    re_path(
        r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", confirm_email, name="account_confirm_email"
    ),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path(
        "resend_confirmation_email/",
        views.resend_confirmation_email,
        name="resend_confirmation_email",
    ),
    path("accounts/verify-email/", confirm_email, name="verify_email"),
    path(
        "accounts/email-verification-sent/",
        email_verification_sent,
        name="account_email_verification_sent",
    ),
    path(
        "accounts/resend-verification-email/",
        views.resend_verification_email,
        name="resend_verification_email",
    ),
    # for video chat
    path("meet/", include("videochat.urls")),
    path("transactions/", include("transactions.urls")),
    path("api/transactions/", include("transactions.api.urls")),
    path("", include("paypal.standard.ipn.urls")),
    # rest api
    path("api/users/", include("users.api.urls")),  # Add this line
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("debug-settings/", show_settings),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("",views.home, name="home"),
    path("job-listing", views.job_listing, name="job-listing"),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import redirect, render

from job.models import Job

# Create your views here.


def job_listing(request):
    jobs = Job.objects.filter(is_available=True)
    context = {"jobs": jobs}
    return render(request, "website/job_listing.html")

templates/website/about_us.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
<div class="container mx-auto py-8">
    <h1 class="text-2xl font-bold mb-4">About Us</h1>
    <p>Welcome to UmEmployed! We are dedicated to connecting job seekers with employers.</p>
</div>
{% endblock %}

templates/website/accessibility.html
{% extends 'base.html' %}

{% block title %}Accessibility{% endblock %}

{% block content %}
<div class="container mx-auto py-8">
    <h1 class="text-2xl font-bold mb-4">Accessibility</h1>
    <p>We are committed to ensuring our platform is accessible to everyone.</p>
</div>
{% endblock %}

templates/website/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  />
</head>
<body class="h-screen">
    <!-- Container -->
    <div class="flex h-full">
        <!-- Main Chat Area -->
        <div class="flex flex-col container mx-auto h-screen overflow-hidden bg-gray-50">
            <!-- Chat Header -->
            <div class="flex  items-center justify-between p-4 bg-[#1e90ff] text-white">
                <h2 class="text-lg font-semibold">John Doe</h2>
                <button class="p-2 rounded-lg hover:bg-blue-400">
                    <i class="fas fa-ellipsis-h"></i>
                </button>
            </div>

            <!-- Chat Messages -->
            <div class="flex-1 h-[75%] overflow-y-auto p-4 overflow-y-auto space-y-4 ">
                <!-- Sent Message -->
                <div class="flex justify-end">
                    <div class="bg-blue-500 text-white p-3 rounded-lg max-w-sm">
                        Hello, how can I help you?
                    </div>
                </div>
                <!-- Received Message -->
                <div class="flex justify-start">
                    <div class="bg-gray-200 text-gray-800 p-3 rounded-lg max-w-sm">
                        Hi! I wanted to ask about the job application.
                    </div>
                </div>
                <!-- Repeat for more messages -->
            </div>

            <!-- Message Input -->
            <div class="p-4 bg-white border-t">
                <form class="flex items-center space-x-3">
                    <input
                        type="text"
                        class="flex-1 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400"
                        placeholder="Type your message..."
                    />
                    <button
                        type="submit"
                        class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-400"
                    >
                        <i class="fas fa-paper-plane"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/website/community_guidelines.html
{% extends 'base.html' %}

{% block title %}Community Guidelines{% endblock %}

{% block content %}
<div class="container mx-auto py-8">
    <h1 class="text-2xl font-bold mb-4">Community Guidelines</h1>
    <p>Our community guidelines ensure a safe and respectful environment for all users.</p>
</div>
{% endblock %}

templates/website/contact_us.html
{% extends 'base.html' %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<div class="container mx-auto py-8">
    <h1 class="text-2xl font-bold mb-4">Contact Us</h1>
    <p>If you have any questions, feel free to reach out to us at support@umemployed.com.</p>
</div>
{% endblock %}

templates/website/for_employers.html
{% extends 'base.html' %}

{% block title %}For Employers{% endblock %}

{% block content %}
<div class="container mx-auto py-8">
    <h1 class="text-2xl font-bold mb-4">For Employers</h1>
    <p>Discover how we can help you find the best talent for your company.</p>
</div>
{% endblock %}

templates/website/inbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  />
  <link
  rel="stylesheet"
  href="{% static 'new_design/styles/general.css' %}"
/>
</head>
<body>
  <div class="h-screen overflow-hidden bg-white">
    <!-- Header -->
    <header class=" bg-[#1e90ff] text-white  z-[100]">
      <div class="container mx-auto max-w-5xl flex justify-between items-center p-4">
        <h1 class="text-lg font-semibold">Inbox</h1>
        <ul class="flex space-x-4">
          <li>
            <button class="text-white border  px-2 font-semibold py-2 rounded text-sm hover:bg-blue-400">
              <i class="fas fa-plus"></i> New Message
            </button>
          </li>
          <li>
            <button id="mobileMenuButton" class="sm:hidden">
              <i class="fas fa-bars"></i>
            </button>
          </li>
          <li class="relative hidden sm:block">
            <button
              id="menuButton"
              class="p-2  active:border-[#1e90ff] rounded-lg"
            >
              <i class="fas fa-bars"></i>
            </button>
            <!-- Desktop Menu -->
            <div
              id="desktopMenu"
              class="hidden absolute top-14 right-0 bg-white p-6 w-[300px] border rounded shadow-2xl z-20"
            >
              <div class="content flex flex-col gap-4 mb-8">
                <a
                  href="{% url 'upload' %}"
                  class="menu-item flex items-center gap-2 font-semibold md:hidden hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-building"></i> Resume
                </a>
                <a
                  href="{% url 'home' %}"
                  class="menu-item flex items-center gap-2 font-semibold md:hidden hover:text-[#1e90ff]"
                >
                  <i class="fas fa-briefcase"></i> Browse Jobs
                </a>
                {% if user.is_authenticated %}
                <div
                  class="header text-nowrap items-center flex gap-2 mb-4 bg-blue-200 p-2 rounded-lg"
                >
                  <span
                    class="font-semibold text-xl text-[#1e90ff] rounded-full py-3 px-3.5 bg-blue-100"
                    >
                    {% if user.resume.profile_image %}
                      <img src="{{ user.resume.profile_image.url }}" alt="Profile Image" class="w-10 h-10 rounded-full object-cover">
                    {% else %}
                      <span class="w-[50px] h-[50px] flex items-center justify-center font-semibold text-xl text-[#1e90ff] rounded-full bg-blue-100">
                        <i class="fas fa-user"></i>
                      </span>
                    {% endif %}
                    </span
                  >
                  <span class="overflow-hidden whitespace-nowrap text-ellipsis"
                    >{{user.username}}</span
                  >
              </div>
                <a
                  href="{% url 'notifications:user_notifications' %}"
                  class="menu-item flex items-center gap-2 font-semibold hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-plus-circle"></i> Notifications
                </a>
                <a
                  href="{% url 'messaging:inbox' %}"
                  class="menu-item flex items-center gap-2 font-semibold hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-envelope"></i> Messages
                </a>
                {% if user.is_applicant %}
                  <a
                  href="{% url 'update-resume' %}"
                  class="menu-item flex items-center gap-2 font-semibold hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-cog"></i> Settings
                </a>
                {% elif user.is_recruiter and user.has_company and user_company%}
                    <a
                  href="{% url 'update_company' user_company.id %}"
                  class="menu-item flex items-center gap-2 font-semibold hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-cog"></i> Settings
                </a>
                {% endif %}

              </div>
              <div class="authentication flex flex-col gap-4">
                {% if user.is_applicant %}
                <a
                  href="{% url 'dashboard' %}"
                  class="w-full bg-transparent border px-6 py-3 rounded-full text-[#1e90ff] text-center font-semibold"
                >
                <i class="fas fa-tachometer-alt"></i> Dashboard  

                </a>
                {% elif user.is_recruiter and user.has_company and user_company%}
                  <a
                  href="{% url 'company_dashboard' user_company.id %}"
                  class="w-full bg-transparent border px-6 py-3 rounded-full text-[#1e90ff] text-center font-semibold"
                >
                <i class="fas fa-tachometer-alt"></i> Dashboard  

                </a>
                {% else %}
                {% endif %}
                <a
                  href="{% url 'logout' %}"
                  class="w-full bg-[#1e90ff] text-white px-6 py-3 rounded-full text-center font-semibold"
                >
                  <i class="fas fa-sign-in-alt"></i> Logout
                </a>

                {% else %}
                   <a
                  href="{% url 'change_account_type' %}"
                  class="menu-item flex items-center gap-2 font-semibold hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-plus-circle"></i> Post a job
                </a>
                <a
                  href="{% url 'feature-not-implemented' %}"
                  class="menu-item flex items-center gap-2 font-semibold hover:text-[#1e90ff] transition-colors"
                >
                  <i class="fas fa-envelope"></i> Contact Us
                </a>
              </div>
              <div class="authentication flex flex-col gap-4">
                <a
                  href="{% url 'register-applicant' %}"
                  class="w-full bg-transparent border px-6 py-3 rounded-full text-[#1e90ff] text-center font-semibold"
                >
                  <i class="fas fa-user-plus"></i> Create Account
                </a>
                <a
                  href="{% url 'login' %}"
                  class="w-full bg-[#1e90ff] text-white px-6 py-3 rounded-full text-center font-semibold"
                >
                  <i class="fas fa-sign-in-alt"></i> Login
                </a>
                {% endif %}
              </div>
            </div>
          </li>
        </ul>
     
      </div>
    </header>
  
    <!-- Inbox List -->
    <div class="p-4 overflow-y-auto container max-w-4xl mx-auto h-[calc(100%-4rem)] overflow-y-auto">
      <div class="space-y-4">
        <!-- Message Item -->
        <div class="flex items-center justify-between p-3 bg-white rounded-lg shadow hover:bg-gray-100 cursor-pointer">
          <div class="flex items-center space-x-3">
            <div class="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center">
              <i class="fas fa-user text-blue-500"></i>
            </div>
            <div>
              <p class="font-semibold text-gray-800">John Doe</p>
              <p class="text-sm text-gray-500 truncate">Hi! I’m interested in the position...</p>
            </div>
          </div>
          <span class="text-sm text-gray-400">2m ago</span>
        </div>
        <!-- Repeat for more messages -->
        <div class="flex items-center justify-between p-3 bg-white rounded-lg shadow hover:bg-gray-100 cursor-pointer">
          <div class="flex items-center space-x-3">
            <div class="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center">
              <i class="fas fa-user text-blue-500"></i>
            </div>
            <div>
              <p class="font-semibold text-gray-800">Jane Smith</p>
              <p class="text-sm text-gray-500 truncate">Can you share more details...</p>
            </div>
          </div>
          <span class="text-sm text-gray-400">10m ago</span>
        </div>
        <div class="flex items-center justify-between p-3 bg-white rounded-lg shadow hover:bg-gray-100 cursor-pointer">
          <div class="flex items-center space-x-3">
            <div class="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center">
              <i class="fas fa-user text-blue-500"></i>
            </div>
            <div>
              <p class="font-semibold text-gray-800">Jane Smith</p>
              <p class="text-sm text-gray-500 truncate">Can you share more details...</p>
            </div>
          </div>
          <span class="text-sm text-gray-400">10m ago</span>
        </div>
        <!-- Add more items -->
      </div>
    </div>
  </div>

    <!-- Sidebar -->
    <div
      id="mobileMenu"
      class="fixed h-screen hidden overflow-hidden z-[100]  top-0 left-0 bottom-0 right-0 flex flex-col bg-white max-w-[500px] py-4 px-4 z-100"
    >
      <div class="menu-header flex justify-between items-center mb-6">
        <img
          class="h-[20px] lg:h-[24px]"
          src="{% static 'new_design/logo/png/logo-color.png' %}"
          alt="Logo"
        />
        <button id="removeMobileMenu-btn" class="text-3xl">&times;</button>
      </div>

      {% if user.is_authenticated %}
      <div class="content flex flex-col gap-4 mb-8">
        <a
          href="{% url 'upload' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-building"></i> Resume
        </a>
        <a
          href="{% url 'home' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-briefcase"></i> Browse Jobs
        </a>
        
        <a
          href="{% url 'notifications:user_notifications' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-bell"></i> Notifications  </a>
        <a
          href="{% url 'messaging:inbox' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-envelope"></i> Messages
        </a>
      </div>
      <div
        class="authentication flex flex-col gap-4 absolute bottom-10 right-4 left-4"
      >
        {% if user.is_applicant %}
                <a
                  href="{% url 'dashboard' %}"
                  class="w-full bg-transparent border px-6 py-3 rounded-full text-[#1e90ff] text-center font-semibold"
                >
                <i class="fas fa-tachometer-alt"></i> Dashboard  

                </a>
                {% elif user.is_recruiter and user.has_company and user_company%}
                  <a
                  href="{% url 'company_dashboard' user_company.id %}"
                  class="w-full bg-transparent border px-6 py-3 rounded-full text-[#1e90ff] text-center font-semibold"
                >
                <i class="fas fa-tachometer-alt"></i> Dashboard  

                </a>
                {% else %}
          {% endif %}
        <a
           href="{% url 'logout' %}"
          class="w-full bg-[#1e90ff] text-white px-6 py-3 rounded-full text-center font-semibold"
        >
          <i class="fas fa-sign-in-alt"></i> Logout
        </a>
      </div>


      {% else %}
        <div class="content flex flex-col gap-4 mb-8">
        <a
          href="{% url 'upload' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-building"></i> Companies
        </a>
        <a
          href="{% url 'home' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-briefcase"></i> Browse Jobs
        </a>
        <a
          href="{% url 'feature-not-implemented' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas f </ul>a-plus-circle"></i> Post a Job
        </a>
        <a
          href="{% url 'feature-not-implemented' %}"
          class="menu-item flex items-center gap-2 font-semibold p-2 border-b"
        >
          <i class="fas fa-envelope"></i> Contact Us
        </a>
      </div>
      <div
        class="authentication flex flex-col gap-4 absolute bottom-10 right-4 left-4"
      >
        <a
          href="{% url 'register-applicant' %}"
          class="w-full bg-transparent text-[#1e90ff] border px-6 py-3 rounded-full text-center font-semibold"
        >
          <i class="fas fa-user-plus"></i> Create Account
        </a>
        <a
          href="{% url 'login' %}"
          class="w-full bg-[#1e90ff] text-white px-6 py-3 rounded-full text-center font-semibold"
        >
          <i class="fas fa-sign-in-alt"></i> Login
        </a>
      </div>

      {% endif %}
          </div>
          <script src="{% static 'new_design/scripts/menu1.js' %}"></script>
</body>
</html>

templates/website/te.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hero with Animation</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@400;700&display=swap" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/lottie-web/5.7.4/lottie.min.js"></script>
<style>
  body {
    font-family: 'Montserrat Alternates', sans-serif;
  }
  .hero {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    padding: 20px;
  }
  .hero-text {
    font-size: 1.25rem;
    color: #555;
  }
</style>
</head>
<body>

<section class="hero">
  <h1 class="text-4xl font-bold text-gray-800">Welcome to Our Platform</h1>
  <p class="hero-text">Experience tailored opportunities like never before.</p>

  <!-- Animation container with inline styling -->
  <div id="animation-container" style="width: 300px; height: 300px;"></div>
</section>

<script>
  // Load the animation using Lottie
  lottie.loadAnimation({
    container: document.getElementById('animation-container'), // HTML element for animation
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: './ue.json' // Ensure this path is correct
  });
</script>

</body>
</html>