dashboard/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path("", views.dashboard, name="user_dashboard"),
    path("api/suggested-skills/", views.get_suggested_skills, name="get_suggested_skills"),
    path("update-user-skills/", views.update_user_skills, name="update_user_skills"),
    path("save-job/", views.save_job, name="save_job"),
    path("delete-skill/<int:skill_id>/", views.delete_skill, name="delete_skill"),
    path("paginated_skills/", views.paginated_skills, name="paginated_skills"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path("delete_language/<int:language_id>/", views.delete_language, name="delete_language"),
    path("education/<int:id>/", views.get_education, name="get_education"),
    path("education/<int:id>/delete/", views.delete_education, name="delete_education"),
    path("education/save/", views.save_education, name="save_education"),
    path("add_language/", views.add_language, name="add_language"),
    path("update_country/", views.update_country, name="update_country"),
    path("experience/<int:id>/", views.get_experience_details, name="get_experience_details"),
    path("experience/<int:id>/delete/", views.delete_experience, name="delete_experience"),
    path("experience/save/", views.save_experience, name="save_experience"),
]

job/urls.py
from django.urls import include, path

from . import generate_skills, job_description_algorithm, views
from .gpt_calls import execute_input, generate_mcqs, get_skills_from_chatgpt
from .views import enter_job_description

app_name = "job"


urlpatterns = [
    path("create-job/", views.create_job, name="create-job"),
    path("job_type_view/", views.job_type_view, name="job_type_view"),
    path("update-job/<int:pk>/", views.update_job, name="update-job"),
    path("apply/<int:job_id>/", views.apply_job, name="apply_job"),
    path("details/<int:job_id>/", views.job_details, name="job_details"),
    path("job-details/<int:job_id>/", views.job_listing_details, name="job_listing_details"),
    path("confirm/<int:job_id>/", views.confirm_evaluation, name="confirm_evaluation"),
    path("enter-job-description/", enter_job_description, name="enter_job_description"),
    path("job/<int:job_id>/save/", views.save_job, name="save_job"),
    path(
        "save-job/<int:job_id>/", views.save_job_not_ajax, name="save_job_not_ajax"
    ),  # Add this line
    path("saved-jobs/", views.saved_jobs_view, name="view_saved_jobs"),
    path("saved-job/<int:saved_job_id>/delete/", views.delete_saved_job, name="delete_saved_job"),
    path("results/<int:job_id>/", views.evaluation_results, name="evaluation_results"),
    path("update/<int:job_id>/", views.update_job, name="update_job"),
    path("incomplete-jobs/", views.incomplete_jobs_view, name="incomplete_jobs"),
    path("save_video/", views.save_video, name="save_video"),
    # Compiler path
    path("run-code/", views.run_code, name="run_code"),
    path("success/", views.success_page, name="success_page"),
    path("fail/", views.fail_page, name="fail_page"),
    # skills
    path("select-skills/", views.select_skills, name="select_skills"),
    # quiz
    path("job/<int:job_id>/answer/", views.answer_job_questions, name="answer_job_questions"),
    path(
        "answer/<int:job_id>/success", views.job_application_success, name="job_application_success"
    ),
    path(
        "get_questions_for_skill/<int:skill_id>/",
        views.get_questions_for_skill,
        name="get_questions_for_skill",
    ),
    path("save_responses/", views.save_responses, name="save_responses"),
    path("generate_skills/", get_skills_from_chatgpt, name="generate_skills"),
    path("generate_mcqs/", generate_mcqs, name="generate_mcqs"),
    path("execute_input/", execute_input, name="execute_input"),
    # For generating MCQs per skill when creatung a job, this takes the job_title , the entry level and the skills
    path("generate-questions/", generate_skills.generate_questions_view, name="generate_questions"),
    path(
        "extract-technical-skills/",
        job_description_algorithm.extract_technical_skills_endpoint,
        name="extract_technical_skills",
    ),
    path("applied-jobs/", views.user_applied_jobs, name="applied_jobs"),
    path(
        "withdraw-application/<int:job_id>/",
        views.withdraw_application,
        name="withdraw_application",
    ),
    path("save-job/<int:job_id>/", views.save_job, name="save_job"),
    path("remove-saved-job/<int:job_id>/", views.remove_saved_job, name="remove_saved_job"),
    path("saved-jobs/", views.saved_jobs_view, name="saved_jobs"),
    path(
        "jobs/<int:job_id>/shortlist/<int:candidate_id>/",
        views.shortlist_candidate,
        name="shortlist_candidate",
    ),
    path("jobs/shortlisted/<int:company_id>/", views.shortlisted_candidates, name="shortlisted"),
    path(
        "jobs/<int:job_id>/decline/<int:candidate_id>/",
        views.decline_candidate,
        name="decline_candidate",
    ),
    path("issue/<int:job_id>/", views.report_test, name="report_test"),
]

umemployed/urls.py
from allauth.account.views import confirm_email, email_verification_sent
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import JsonResponse
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny

from users import views
from users.views import CustomConfirmEmailView, custom_404_view, custom_500_view

# Define custom error handlers
handler404 = "users.views.custom_404_view"
handler500 = "users.views.custom_500_view"

schema_view = get_schema_view(
    openapi.Info(
        title="Umemployed API",
        default_version="v1",
        description="API documentation for Umemployed",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="info@umemployed.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(AllowAny,),
)


def show_settings(request):
    return JsonResponse(
        {
            "CSRF_TRUSTED_ORIGINS": settings.CSRF_TRUSTED_ORIGINS,
            "ALLOWED_HOSTS": settings.ALLOWED_HOSTS,
            "SECURE_PROXY_SSL_HEADER": settings.SECURE_PROXY_SSL_HEADER,
            "USE_X_FORWARDED_HOST": settings.USE_X_FORWARDED_HOST,
        }
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/user/", include("users.urls")),
    path("api/users/", include("users.api.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("jobs/", views.home, name="home"),
    path("", views.index, name="index"),
    path("accounts/", include("allauth.urls")),
    path("social-auth/", include(("social_django.urls", "social"), namespace="social")),
    # urls for the password reset with email
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="password_reset/passwordReset.html"),
        name="reset_password",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/passwordResetSent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/passwordResetForm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/passwordResetDone.html"
        ),
        name="password_reset_complete",
    ),
    # for the company app
    path("company/", include("company.urls")),
    path("api/company/", include("company.api.urls")),
    # for the resume app
    path("resume/", include("resume.urls")),
    path("api/resume/", include("resume.api.urls")),
    path("job/", include("job.urls")),
    path("api/job/", include("job.api.urls")),
    path("jobs/", include("website.urls")),
    path("onboarding/", include("onboarding.urls")),
    path("assessments/", include("asseessments.urls")),
    path("posts/", include("social_features.urls")),
    path("messages/", include("messaging.urls")),
    path("api/messages/", include("messaging.api.urls")),
    path("notifications/", include("notifications.urls")),
    path("api/notifications/", include("notifications.api.urls")),
    re_path(
        r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", confirm_email, name="account_confirm_email"
    ),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path(
        "resend_confirmation_email/",
        views.resend_confirmation_email,
        name="resend_confirmation_email",
    ),
    path("accounts/verify-email/", confirm_email, name="verify_email"),
    path(
        "accounts/email-verification-sent/",
        email_verification_sent,
        name="account_email_verification_sent",
    ),
    path(
        "accounts/resend-verification-email/",
        views.resend_verification_email,
        name="resend_verification_email",
    ),
    # for video chat
    path("meet/", include("videochat.urls")),
    path("transactions/", include("transactions.urls")),
    path("api/transactions/", include("transactions.api.urls")),
    path("", include("paypal.standard.ipn.urls")),
    # rest api
    path("api/users/", include("users.api.urls")),  # Add this line
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("debug-settings/", show_settings),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
import pycountry
from django import forms

from resume.models import Language, UserLanguage, UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["country"]


class UserLanguageForm(forms.ModelForm):
    class Meta:
        model = UserLanguage
        fields = ["language"]

    def __init__(self, *args, **kwargs):
        super(UserLanguageForm, self).__init__(*args, **kwargs)
        self.fields["language"].queryset = Language.objects.all()


from resume.models import Education


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ["institution_name", "degree", "graduation_year"]


from resume.models import WorkExperience


class WorkExperienceForm(forms.ModelForm):
    class Meta:
        model = WorkExperience
        fields = ["company_name", "role", "start_date", "end_date"]
        widgets = {
            "start_date": forms.DateInput(attrs={"type": "date"}),
            "end_date": forms.DateInput(attrs={"type": "date"}),
        }

job/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget

from resume.models import Skill, SkillCategory

from .models import MCQ, ApplicantAnswer, Job


class CreateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = [
            "title",
            "hire_number",
            "job_location_type",
            "job_type",
            "location",
            "salary_range",
            "category",
        ]  # Removed 'responsibilities' and 'ideal_candidate'

    category = forms.ModelChoiceField(queryset=SkillCategory.objects.all())
    widgets = {
        "location": forms.Select(
            attrs={
                "class": "border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]",
                "id": "job-location",
            }
        )
    }


class JobDescriptionForm(forms.Form):
    """
    Form for entering job description, responsibilities, and ideal candidate details with CKEditor.

    Attributes:
        description (CharField): CKEditorWidget field for job description.
        responsibilities (CharField): CKEditorWidget field for job responsibilities.
        ideal_candidate (CharField): CKEditorWidget field for ideal candidate description.
    """

    description = forms.CharField(widget=CKEditor5Widget())
    responsibilities = forms.CharField(widget=CKEditor5Widget())
    ideal_candidate = forms.CharField(widget=CKEditor5Widget())

    class Meta:
        model = Job
        fields = ["description", "responsibilities", "ideal_candidate"]


class JobTypeForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["job_type", "experience_levels", "weekly_ranges", "shifts"]
        widgets = {
            "job_type": forms.HiddenInput(),
            "experience_levels": forms.HiddenInput(),
            "weekly_ranges": forms.HiddenInput(),
            "shifts": forms.HiddenInput(),
        }


class SkillForm(forms.ModelForm):
    """
    Form for entering required skills for a job.

    Attributes:
        extracted_skills (CheckboxSelectMultiple): Checkbox field for selecting extracted skills.
        level (ChoiceField): Field for selecting the skill level.
    """

    LEVEL_CHOICES = [
        ("Beginner", "Beginner"),
        ("Mid", "Mid"),
        ("Expert", "Expert"),
    ]

    level = forms.ChoiceField(choices=LEVEL_CHOICES)

    class Meta:
        model = Job
        fields = ["extracted_skills", "level"]
        widgets = {
            "extracted_skills": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        job_instance = kwargs.pop("job_instance")
        super().__init__(*args, **kwargs)

        # Initialize extracted_skills with the job's extracted skills
        if job_instance.extracted_skills.exists():
            self.fields["extracted_skills"].initial = job_instance.extracted_skills.all()

    def clean(self):
        cleaned_data = super().clean()
        # Perform additional validation if necessary
        return cleaned_data


class JobUpdateForm(forms.ModelForm):
    ideal_candidate = CKEditor5Widget()
    description = CKEditor5Widget()
    responsibilities = CKEditor5Widget()
    benefits = CKEditor5Widget()

    class Meta:
        model = Job
        fields = [
            "title",
            "hire_number",
            "job_location_type",
            "location",
            "salary",
            "requirements",
            "extracted_skills",
            "ideal_candidate",
            "is_available",
            "description",
            "responsibilities",
            "benefits",
            "level",
            "category",
            "job_type",
            "experience_levels",
            "weekly_ranges",
            "shifts",
        ]
        widgets = {
            "requirements": forms.CheckboxSelectMultiple,
            "extracted_skills": forms.CheckboxSelectMultiple,
        }


class UpdateJobForm(forms.ModelForm):
    """
    Form for updating job details.

    Excludes 'user' and 'company' fields.

    Attributes:
        model (Job): The Job model.
        exclude (tuple): Fields to exclude from the form.
    """

    class Meta:
        model = Job
        exclude = ("user", "company")


class ApplicantAnswerForm(forms.ModelForm):
    """
    Form for entering applicant's answers to MCQs.

    Attributes:
        model (ApplicantAnswer): The ApplicantAnswer model.
        fields (list): All fields of the ApplicantAnswer model.
    """

    class Meta:
        model = ApplicantAnswer
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        """
        Initialize the form.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)

templates/dashboard/recruiterDashboard/addJob.html
{% extends 'resume/base.html' %}
{% load static %}
{% block custom_css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}
{% block content %}
  <main class="flex-grow px-2 md:px-3 w-[98%] lg:w-[100%] mx-auto container">
    <form id="addJob" class="w-full md:w-[65%] mx-auto" method="post">
      {% csrf_token %}
      <h1 class="text-3xl font-bold text-gray-800 my-5">Add a job</h1>
      <div class="input-wrap mb-8">
        <label for="job-title" class="text-[17px] font-[500] text-gray-800">Job title</label><br />
        <input class="border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]" type="text" placeholder="ex(Asiistant Manager)" name="title" id="job-title" required />
      </div>
      <div class="input-wrap mb-8">
        <label for="hire-number" class="text-[17px] font-[500] text-gray-800">Number of persons to hire for this job</label><br />
        <select class="border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]" name="hire_number" id="hire-number" required>
          <option value="" selected>Choose an option</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
          <option value="more">More</option>
        </select>
      </div>
      <div class="input-wrap mb-8">
        <label for="salary_range" class="text-[17px] font-[500] text-gray-800">Salary Range</label><br />
        <select class="border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]" name="salary_range" id="salary_range" required>
          <option value="30000-50000">$30,000 - $50,000</option>
          <option value="50001-70000">$50,001 - $70,000</option>
          <option value="70001-100000">$70,001 - $100,000</option>
          <option value="100001-150000">$100,001 - $150,000</option>
          <option value="150001+">$150,001 and above</option>
        </select>
      </div>

      <div class="input-wrap mb-8">
        <label for="job-location" class="text-[17px] font-[500] text-gray-800">Job Location</label><br />
        <div class="border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]" name="location" id="job-location" required>{{ form.location }}</div>
      </div>

      <!-- Job Location Type -->
      <div class="input-wrap mb-8">
        <label for="job-location-type" class="text-[17px] font-[500] text-gray-800">Job Location Type</label><br />
        <select class="border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]" name="job_location_type" id="job-location-type" required>
          <option value="" selected>Choose an option</option>
          <option value="remote">Remote</option>
          <option value="onsite">Onsite</option>
          <option value="hybrid">Hybrid</option>
          <option value="internship">Internship</option>
        </select>
      </div>

      <!-- Job Type -->
      <div class="input-wrap mb-8">
        <label for="job-type" class="text-[17px] font-[500] text-gray-800">Job Type</label><br />
        <select class="border border-gray-400 p-[11px] w-full bg-transparent rounded-lg outline-1 outline-[#1e90ff]" name="job_type" id="job-type" required>
          <option value="" selected>Choose an option</option>
          <option value="Full_time">Full-Time</option>
          <option value="Part_time">Part-Time</option>
          <option value="Contract">Contract</option>
          <option value="Temporary">Temporary</option>
          <option value="Internship">Internship</option>
          <option value="Freelance">Freelance</option>
        </select>
      </div>

      <div class="input-wrap mb-8">
        <label for="id_category">Category:</label>
        <select name="category" id="id_category">
          {% for category in form.category.field.queryset %}
            <option value="{{ category.id }}">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
      <!-- Other fields and submit button -->
      <div class="btn-wrap text-end mt-0 mb-5">
        <button type="submit" class="px-5 py-2 text-white font-bold bg-[#1e90ff] rounded-lg">Next <span class="text-[20px]">&RightArrow;</span></button>
      </div>
    </form>
  </main>
  {% block footer %}
  {% endblock footer %}
  <footer class="text-gray-800 text-center p-3">
    <div class="flex flex-col sm:flex-row justify-center gap-2 items-center">
      <p class="text-sm">© 2024 UmEmployed. All rights reserved.</p>
      <div class="flex space-x-4 items-center">
        <a
          href="{% url 'feature-not-implemented' %}"
          class="text-white hover:text-gray-300"
        >
          <i class="fab fa-twitter text-black"></i>
        </a>
        <a
          href="{% url 'feature-not-implemented' %}"
          class="text-white hover:text-gray-300"
        >
          <i class="fab fa-linkedin text-black"></i>
        </a>
        <a
          href="{% url 'feature-not-implemented' %}"
          class="text-white hover:text-gray-300"
        >
          <i class="fab fa-facebook text-black"></i>
        </a>
        <img src="{% static 'new_design/logo/privacy.jpeg' %}" alt="" class="w-10 h-5">
      </div>
      <div class="text-sm ">

        <a href="{% url 'feature-not-implemented' %}" class="hover:text-gray-300"
          >Privacy Policy
          </a
        >

        <a href="{% url 'feature-not-implemented' %}" class="hover:text-gray-300">Contact Us</a>
      </div>
    </div>
  </footer>

  <script type="module" src="{% static 'scripts/addjob.js' %}"></script>
  <script type="module" src="{% static 'scripts/dashboard.js' %}"></script>
{% endblock %}

templates/dashboard/recruiterDashboard/jobDescription.html
{% extends 'resume/base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
<script src="https://cdn.tailwindcss.com"></script>

<!-- Loader CSS -->

<style>
.loader .logo-loader img{
    width: 150px;
    height: 150px;
    border-radius: 50%;
    background-size: cover;
    margin: 0 auto;
}


@keyframes blink {
    0%,
    50%,
    100% {
        opacity: 1;
    }

    25%,
    75% {
        opacity: 0;
    }
}

.blinking {
    animation: blink 6s infinite;
}
</style>
{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
    <main class="flex-grow px-2 md:px-3 w-[98%] lg:w-[100%] mx-auto container">
    <!-- Loader HTML -->
<div id="loader" class="hidden fixed inset-0 bg-gray-200 bg-opacity-2 flex items-center justify-center z-50">
    <div class="loader">
        <div class="logo-loader blinking">
            <img style="no-repeat center center" src="{% static 'build/logo/logo-color.png' %}">
        </div>
        <br><br>
        <span><p>Processing, this might take some seconds.</p><span>
    </div>
</div>

<!-- Add Job Form -->
<form id="addJob" class="w-full md:w-[65%] mx-auto" method="post" action="{% url 'job:enter_job_description' %}">
    {% csrf_token %}
    <h1 class="text-3xl font-bold text-gray-800 my-5">Complete the following job details.</h1>

    <!-- Job Description Field -->
    <div class="input-wrap mb-8">
        <label for="job-description" class="text-[17px] font-[500] text-gray-800">Job Description</label><br />
        {{ form.description }}
    </div>

    <!-- Responsibilities Field -->
    <hr class="my-14 border-gray-500" />
    <div class="input-wrap mb-8">
        <label for="responsibilities" class="text-[17px] font-[500] text-gray-800">Responsibilities</label><br />
        {{ form.responsibilities }}
    </div>

    <!-- Ideal Candidate/Qualifications Field -->
    <div class="input-wrap mb-8">
        <label for="ideal_candidate" class="text-[17px] font-[500] text-gray-800">Qualifications</label><br />
        {{ form.ideal_candidate }}
    </div>

    <!-- Submit Button -->
    <div class="btn-wrap text-end mb-5 mr-10">
        <button type="submit" class="inline-block px-4 py-2 text-white bg-blue-600 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
            Next <span class="text-[20px]">&RightArrow;</span>
        </button>
    </div>
</form>


</main>
{% block footer %}
  {% endblock footer %}
  <footer class="text-gray-800 text-center p-3">
    <div class="flex flex-col sm:flex-row justify-center gap-2 items-center">
      <p class="text-sm">© 2024 UmEmployed. All rights reserved.</p>
      <div class="flex space-x-4 items-center">
        <a
          href="{% url 'feature-not-implemented' %}"
          class="text-white hover:text-gray-300"
        >
          <i class="fab fa-twitter text-black"></i>
        </a>
        <a
          href="{% url 'feature-not-implemented' %}"
          class="text-white hover:text-gray-300"
        >
          <i class="fab fa-linkedin text-black"></i>
        </a>
        <a
          href="{% url 'feature-not-implemented' %}"
          class="text-white hover:text-gray-300"
        >
          <i class="fab fa-facebook text-black"></i>
        </a>
        <img src="{% static 'new_design/logo/privacy.jpeg' %}" alt="" class="w-10 h-5">
      </div>
      <div class="text-sm ">

        <a href="{% url 'feature-not-implemented' %}" class="hover:text-gray-300"
          >Privacy Policy
          </a
        >

        <a href="{% url 'feature-not-implemented' %}" class="hover:text-gray-300">Contact Us</a>
      </div>
    </div>
  </footer>
{% block extra_js %}
    {{ form.media }}
{% endblock %}
<!-- JavaScript for handling form submission and loader -->
<script>
document.addEventListener('DOMContentLoaded', function () {
    const addJobForm = document.getElementById('addJob');
    const loader = document.getElementById('loader');

    addJobForm.addEventListener('submit', function () {
        loader.classList.remove('hidden');
    });
});
</script>


    <script type="module" src="{% static 'scripts/addjob.js' %}"></script>
    <script type="module" src="{% static 'scripts/dashboard.js' %}"></script>
  {% endblock %}